spring.application.name=monitoring

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/monitoring_db
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect